services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2-distroless
    container_name: pocket-id
    restart: unless-stopped
    user: 1000:1000
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    env_file: .env
    volumes:
      - ./data:/app/data
    # Optional healthcheck
    healthcheck:
      test: ['CMD', '/app/pocket-id', 'healthcheck']
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - pocket-id
    labels:
      caddy: id.$DOMAIN
      caddy.reverse_proxy: "{{ upstreams 1411 }}"
      caddy.import_0: tls
      caddy.import_1: security-headers

      homepage.group: $DOMAIN
      homepage.weight: 10
      homepage.name: Pocket-ID
      homepage.icon: pocket-id.svg
      homepage.description: Simple OIDC provider with passkey authentication
      homepage.href: https://id.$DOMAIN
      homepage.siteMonitor: https://id.$DOMAIN

networks:
  pocket-id:
    name: pocket-id
    driver: bridge
