---
services:
  gotify:
    image: ghcr.io/gotify/server:2.9.1
    container_name: gotify
    user: 1000:1000
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    volumes:
      - './gotify_data:/app/data'
    environment:
      GOTIFY_SERVER_PORT: 8080
    env_file: .env  # put GOTIFY_DEFAULTUSER_PASS here
    networks:
      - gotify
    labels:
      caddy: gotify.$DOMAIN
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
      caddy.import_0: tls
      caddy.import_1: security-headers

      homepage.group: $DOMAIN Monitoring
      homepage.weight: 20
      homepage.name: Gotify
      homepage.icon: gotify.png
      homepage.href: https://gotify.$DOMAIN
      homepage.siteMonitor: https://gotify.$DOMAIN
      homepage.widget.type: gotify
      homepage.widget.url: https://gotify.$DOMAIN
      homepage.widget.key: $GOTIFY_HOMEPAGE_KEY

networks:
  gotify:
    name: gotify
    driver: bridge
