services:
  redlib:
    image: quay.io/redlib/redlib:latest
    # image: quay.io/redlib/redlib:latest-arm # uncomment if you use arm64
    # image: quay.io/redlib/redlib:latest-armv7 # uncomment if you use armv7
    container_name: redlib
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    env_file: .env
    #ports:
    #- 127.0.0.2:8080:8080 # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy
    networks:
      - redlib
    labels:
      caddy: https://redlib.$DOMAIN
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
      caddy.import_1: security-headers
      caddy.import_2: geofilter

      homepage.group: $DOMAIN
      homepage.weight: 250
      homepage.name: Redlib
      homepage.icon: redlib.svg
      homepage.description: Private front-end for Reddit
      homepage.href: https://redlib.$DOMAIN
      homepage.siteMonitor: https://redlib.$DOMAIN/info

networks:
  redlib:
    name: redlib
