services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    #ports:
     #- "9000:9000"
    volumes:
      - ./config:/var/opt/thelounge

