services:
  aonsoku:
    image: ghcr.io/victoralvesf/aonsoku:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - navidrome
    labels:
      caddy: aonsoku.$DOMAIN
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
      caddy.import_1: security-headers
      caddy.import_2: geofilter

networks:
  navidrome:
    external: true
