services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    user: 1000:1000
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./downloads:/downloads
    labels:
      caddy: metube.$DOMAIN
      caddy.reverse_proxy: "{{ upstreams 8081 }}"
      caddy.import_1: security-headers
      caddy.import_2: tinyauth_forwarder *

      tinyauth.apps.metube.config.domain: metube.$DOMAIN
      tinyauth.apps.metube.oauth.groups: metube  # group from pocket-id
    networks:
      caddy:

networks:
  caddy:
    external: true
